import type { StaffMember, Practice, AlertLog } from "./types";

export const mockPractice: Practice = {
  id: "practice-1",
  name: "Westside Family Medicine",
  specialty: "Family Medicine",
  state: "Wisconsin",
  timezone: "America/Chicago",
  plan: "professional",
};

export const mockStaff: StaffMember[] = [
  {
    id: "staff-1",
    name: "Dr. Sarah Chen",
    role: "MD",
    email: "sarah.chen@westsidefm.com",
    credentials: [
      {
        id: "cred-1",
        type: "state_license",
        label: "State Medical License — Wisconsin",
        licenseNumber: "MD-12345678",
        issuingState: "WI",
        expiryDate: "2026-06-15",
        alertCC: false,
        staffId: "staff-1",
      },
      {
        id: "cred-2",
        type: "dea",
        label: "DEA Registration",
        licenseNumber: "FC1234567",
        expiryDate: "2026-09-30",
        alertCC: false,
        staffId: "staff-1",
      },
      {
        id: "cred-3",
        type: "board_cert",
        label: "Board Certification — ABFM Family Medicine",
        issuingOrg: "American Board of Family Medicine",
        expiryDate: "2028-12-31",
        alertCC: false,
        staffId: "staff-1",
      },
      {
        id: "cred-4",
        type: "malpractice",
        label: "Malpractice Insurance",
        expiryDate: "2026-04-01",
        alertCC: false,
        staffId: "staff-1",
      },
      {
        id: "cred-5",
        type: "bls_acls",
        label: "BLS Certification",
        expiryDate: "2027-03-15",
        alertCC: false,
        staffId: "staff-1",
      },
    ],
  },
  {
    id: "staff-2",
    name: "Marcus Williams",
    role: "RN",
    email: "marcus.w@westsidefm.com",
    credentials: [
      {
        id: "cred-6",
        type: "state_license",
        label: "State Nursing License — Wisconsin",
        licenseNumber: "RN-9876543",
        issuingState: "WI",
        expiryDate: "2026-08-20",
        alertCC: true,
        staffId: "staff-2",
      },
      {
        id: "cred-7",
        type: "bls_acls",
        label: "BLS/ACLS Certification",
        expiryDate: "2026-03-13",
        alertCC: true,
        staffId: "staff-2",
      },
      {
        id: "cred-8",
        type: "malpractice",
        label: "Malpractice Insurance",
        expiryDate: "2026-11-01",
        alertCC: false,
        staffId: "staff-2",
      },
    ],
  },
  {
    id: "staff-3",
    name: "Patricia Lopez",
    role: "NP",
    email: "p.lopez@westsidefm.com",
    credentials: [
      {
        id: "cred-9",
        type: "state_license",
        label: "State NP License — Wisconsin",
        licenseNumber: "NP-4567890",
        issuingState: "WI",
        expiryDate: "2026-12-31",
        alertCC: false,
        staffId: "staff-3",
      },
      {
        id: "cred-10",
        type: "dea",
        label: "DEA Registration",
        licenseNumber: "ML7654321",
        expiryDate: "2027-06-15",
        alertCC: false,
        staffId: "staff-3",
      },
      {
        id: "cred-11",
        type: "board_cert",
        label: "Board Certification — AANP",
        issuingOrg: "American Academy of Nurse Practitioners",
        expiryDate: "2027-08-31",
        alertCC: false,
        staffId: "staff-3",
      },
      {
        id: "cred-12",
        type: "bls_acls",
        label: "BLS Certification",
        expiryDate: "2026-05-10",
        alertCC: false,
        staffId: "staff-3",
      },
    ],
  },
  {
    id: "staff-4",
    name: "James Rodriguez",
    role: "PA",
    email: "j.rodriguez@westsidefm.com",
    credentials: [
      {
        id: "cred-13",
        type: "state_license",
        label: "State PA License — Wisconsin",
        licenseNumber: "PA-1122334",
        issuingState: "WI",
        expiryDate: "2026-02-28",
        alertCC: false,
        staffId: "staff-4",
      },
      {
        id: "cred-14",
        type: "board_cert",
        label: "Board Certification — NCCPA",
        issuingOrg: "National Commission on Certification of Physician Assistants",
        expiryDate: "2027-12-31",
        alertCC: false,
        staffId: "staff-4",
      },
      {
        id: "cred-15",
        type: "dea",
        label: "DEA Registration",
        licenseNumber: "FR9876543",
        expiryDate: "2026-07-31",
        alertCC: false,
        staffId: "staff-4",
      },
    ],
  },
  {
    id: "staff-5",
    name: "Lisa Thompson",
    role: "MA",
    email: "l.thompson@westsidefm.com",
    credentials: [
      {
        id: "cred-16",
        type: "bls_acls",
        label: "BLS Certification",
        expiryDate: "2026-04-15",
        alertCC: true,
        staffId: "staff-5",
      },
      {
        id: "cred-17",
        type: "custom",
        label: "CMA Certification",
        issuingOrg: "AAMA",
        expiryDate: "2027-10-01",
        alertCC: false,
        staffId: "staff-5",
      },
    ],
  },
];

export const mockAlertLogs: AlertLog[] = [
  {
    id: "alert-1",
    credentialId: "cred-13",
    credentialLabel: "State PA License — Wisconsin",
    staffName: "James Rodriguez",
    type: "7_day",
    sentAt: "2026-02-21T09:00:00Z",
    delivered: true,
  },
  {
    id: "alert-2",
    credentialId: "cred-13",
    credentialLabel: "State PA License — Wisconsin",
    staffName: "James Rodriguez",
    type: "30_day",
    sentAt: "2026-01-29T09:00:00Z",
    delivered: true,
  },
  {
    id: "alert-3",
    credentialId: "cred-7",
    credentialLabel: "BLS/ACLS Certification",
    staffName: "Marcus Williams",
    type: "7_day",
    sentAt: "2026-03-06T09:00:00Z",
    delivered: true,
  },
  {
    id: "alert-4",
    credentialId: "cred-4",
    credentialLabel: "Malpractice Insurance",
    staffName: "Dr. Sarah Chen",
    type: "30_day",
    sentAt: "2026-03-01T09:00:00Z",
    delivered: true,
  },
  {
    id: "alert-5",
    credentialId: "cred-12",
    credentialLabel: "BLS Certification",
    staffName: "Patricia Lopez",
    type: "90_day",
    sentAt: "2026-02-09T09:00:00Z",
    delivered: true,
  },
];
